# GROCERY STORE SALES
ON WHICH DAY STORE SALES THE HIGHEST ?

# IMPORT THE LIBRARIES

In [1]:
import pandas as pd
import numpy as np

In [4]:
np.random.seed(0)
product_sales=np.random.randint(10,99,size=(6,5))
product_sales


array([[54, 57, 74, 77, 77],
       [19, 93, 31, 46, 97],
       [80, 98, 98, 22, 68],
       [75, 49, 97, 56, 98],
       [91, 47, 35, 87, 82],
       [19, 30, 90, 79, 89]])

In [5]:
product_sales_df=pd.DataFrame(product_sales,
                             index=["MONDAY","TUESDAY","WEDNESDAY","THRUSDAY","FRIDAY","SATURDAY"],
                             columns=["PIZZA","BURGER","COLD DRINKS","HOT DOGS","FRIES"])
product_sales_df

PIZZA  BURGER  COLD DRINKS  HOT DOGS  FRIES
MONDAY        54      57           74        77     77
TUESDAY       19      93           31        46     97
WEDNESDAY     80      98           98        22     68
THRUSDAY      75      49           97        56     98
FRIDAY        91      47           35        87     82
SATURDAY      19      30           90        79     89

# PRICE OF PRODUCTS

In [6]:
price=np.array([299,99,49,80,90])
price

array([299,  99,  49,  80,  90])

In [7]:
price_df=pd.DataFrame(price.reshape(1,5),
                     index=["PRICE"],
                     columns=["PIZZA","BURGER","COLD DRINKS","HOT DOGS","FRIES"])
price_df

PIZZA  BURGER  COLD DRINKS  HOT DOGS  FRIES
PRICE    299      99           49        80     90

# TRANSPOSE OF PRODUCT SALSE

In [8]:
product_sales_T=product_sales.T
product_sales_T

array([[54, 19, 80, 75, 91, 19],
       [57, 93, 98, 49, 47, 30],
       [74, 31, 98, 97, 35, 90],
       [77, 46, 22, 56, 87, 79],
       [77, 97, 68, 98, 82, 89]])

# TOTAL SALES 
DOT PRODUCT VS ELEMENT WISE

In [9]:
total_sales=price.dot(product_sales_T)
total_sales

array([38505, 28817, 46304, 45329, 47917, 27391])

# TOTAL SALES DATAFRAME

In [20]:
total_sales_df=pd.DataFrame(total_sales.reshape(1,6),
                           index=["TOTAL PRICE ($)"],
                           columns=["MONDAY","TUESDAY","WEDNESDAY","THRUSDAY","FRIDAY","SATURDAY"])
total_sales_df

MONDAY  TUESDAY  WEDNESDAY  THRUSDAY  FRIDAY  SATURDAY
TOTAL PRICE ($)   38505    28817      46304     45329   47917     27391

# TRANSPOSE THE TOTAL SALES

In [21]:
total_sales_df_T=total_sales_df.T
total_sales_df_T

TOTAL PRICE ($)
MONDAY               38505
TUESDAY              28817
WEDNESDAY            46304
THRUSDAY             45329
FRIDAY               47917
SATURDAY             27391

# JOIN THE TOTAL SALES WITH PRODUCT SALES DATA FRAME

In [22]:
product_sales_df["TOTAL SALES ($)"]=total_sales_df_T
product_sales_df

PIZZA  BURGER  COLD DRINKS  HOT DOGS  FRIES  $ Total SALES  \
MONDAY        54      57           74        77     77          38505   
TUESDAY       19      93           31        46     97          28817   
WEDNESDAY     80      98           98        22     68          46304   
THRUSDAY      75      49           97        56     98          45329   
FRIDAY        91      47           35        87     82          47917   
SATURDAY      19      30           90        79     89          27391   

           TOTAL SALES ($)  
MONDAY               38505  
TUESDAY              28817  
WEDNESDAY            46304  
THRUSDAY             45329  
FRIDAY               47917  
SATURDAY             27391

In [25]:
product_sales_df.to_csv("EXPORTED GROCERY PRODUCT SALES.CSV")